kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: publish-hyperkube-amd64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: rancher/hyperkube
      tag: "${DRONE_TAG}-amd64"
    when:
      event:
        - tag
---
kind: pipeline
name: manifest

steps:
  - name: push-manifest
    image: plugins/manifest:1.0.2
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "rancher/hyperkube:${DRONE_TAG}"
      template: "rancher/hyperkube:${DRONE_TAG}-ARCH"
      platforms:
        - linux/amd64
    when:
      event:
        - tag
depends_on:
- amd64
